In [ ]:
!pip install -q snscrape

In [ ]:
import snscrape.modules.twitter as sntwitter
import pandas as pd


In [ ]:
# Created a list to append all tweet attributes(data)
attributes_container = []
# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:wizkhalifa').get_items()):
    if i>999:
        break
    attributes_container.append([tweet.content])

# Creating a dataframe from the tweets list above
# tweets_df = pd.DataFrame(attributes_container, columns=["Tweets"])

In [ ]:
# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:timesofindia').get_items()):
    if i>999:
        break
    attributes_container.append([tweet.content])

for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:cnni').get_items()):
    if i>999:
        break
    attributes_container.append([tweet.content])

for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:sonamakapoor').get_items()):
    if i>999:
        break
    attributes_container.append([tweet.content])
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('from:ABPNews').get_items()):
    if i>999:
        break
    attributes_container.append([tweet.content])


# Creating a dataframe from the tweets list above
tweets_df = pd.DataFrame(attributes_container, columns=["Tweets"])

In [ ]:
tweets_df

Tweets
0     TAYLORS!! Bring in the new year with me. I’m p...
1         They day party set up https://t.co/WcmoZZN1ss
2                Me in the club https://t.co/UGOdQftnh5
3     Being able to speak well has gotten me very fa...
4       Pull out the weed and everyone becomes friends.
...                                                 ...
4995  बीजेपी ने पश्चिम बंगाल की सीएम ममता बनर्जी के ...
4996  LIVE: अपना-अपना दांव, कौन जीतेगा चुनाव?  \n\n#...
4997  LIVE : देखिए PM Modi के क्षेत्र का क्या है चुन...
4998  चीन में राष्ट्रपति शी जिनपिंग के खिलाफ क्यों स...
4999  लोकायुक्त डीजी कैलाश मकवाना के ट्रांसफर पर बेट...

[5000 rows x 1 columns]

In [ ]:
lis = []
for i in range(0, 5000):
  if (i<1000):
    lis.append(("wizkhalifa"))
  elif (i>999) and (i<2000):
    lis.append('timesofindia')
  elif (i>1999) and (i<3000):
    lis.append('cnni')
  elif (i>2999) and (i<4000):
    lis.append('sonamakapoor')
  elif (i>3999) and (i<5000):
    lis.append('ABPNews')

tweets_df['author'] = lis

In [ ]:
tweets_df.to_csv('wizkhalifa_task1.csv',index=False) # relative position

In [ ]:
path = '/content/drive/MyDrive/Project_Phase_1'
from google.colab import files
files.download("wizkhalifa_task1.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
data = pd. read_csv("wizkhalifa_task1.csv")

In [ ]:
data

Date Created  \
0     2022-11-29 19:22:17+00:00   
1     2022-11-28 09:26:14+00:00   
2     2022-11-25 21:31:14+00:00   
3     2022-11-25 17:25:03+00:00   
4     2022-11-23 22:36:39+00:00   
...                         ...   
996   2022-02-15 23:29:17+00:00   
997   2022-02-15 20:55:39+00:00   
998   2022-02-15 02:21:18+00:00   
999   2022-02-15 02:03:34+00:00   
1000  2022-02-15 02:02:11+00:00   

                                                 Tweets  
0     People who used to smoke weed but don’t anymor...  
1                  👀 @McQueenVF https://t.co/4WEo4o7PhX  
2                  🤯 @McQueenVF https://t.co/rae8AfoLLY  
3     Tonight at 8pm ET only on ESPN+ PPV the riches...  
4     Still got some mystery boxes in stock for y’al...  
...                                                 ...  
996   Tellin someone to take a hike is actually real...  
997   Gotta look fresh in that @TaylorGang drip 💧💧💧\...  
998                @QuadWoofer Let the music save em 🙏🏽  
999                        Yoga finna be fire this week  
1000   Ima help y’all’s over thinkin brains be at peace  

[1001 rows x 2 columns]

In [ ]:
import string
import re
import string
import numpy as np

In [ ]:
tweets_df

Tweets      author
0     TAYLORS!! Bring in the new year with me. I’m p...  wizkhalifa
1         They day party set up https://t.co/WcmoZZN1ss  wizkhalifa
2                Me in the club https://t.co/UGOdQftnh5  wizkhalifa
3     Being able to speak well has gotten me very fa...  wizkhalifa
4       Pull out the weed and everyone becomes friends.  wizkhalifa
...                                                 ...         ...
4995  बीजेपी ने पश्चिम बंगाल की सीएम ममता बनर्जी के ...     ABPNews
4996  LIVE: अपना-अपना दांव, कौन जीतेगा चुनाव?  \n\n#...     ABPNews
4997  LIVE : देखिए PM Modi के क्षेत्र का क्या है चुन...     ABPNews
4998  चीन में राष्ट्रपति शी जिनपिंग के खिलाफ क्यों स...     ABPNews
4999  लोकायुक्त डीजी कैलाश मकवाना के ट्रांसफर पर बेट...     ABPNews

[5000 rows x 2 columns]

In [ ]:
####  Task 2
tweets_cleaned = tweets_df[['Tweets']].copy()
tweets_cleaned['Tweets'] = tweets_cleaned['Tweets'].str.lower()

tweets_cleaned

Tweets
0     taylors!! bring in the new year with me. i’m p...
1         they day party set up https://t.co/wcmozzn1ss
2                me in the club https://t.co/ugodqftnh5
3     being able to speak well has gotten me very fa...
4       pull out the weed and everyone becomes friends.
...                                                 ...
4995  बीजेपी ने पश्चिम बंगाल की सीएम ममता बनर्जी के ...
4996  live: अपना-अपना दांव, कौन जीतेगा चुनाव?  \n\n#...
4997  live : देखिए pm modi के क्षेत्र का क्या है चुन...
4998  चीन में राष्ट्रपति शी जिनपिंग के खिलाफ क्यों स...
4999  लोकायुक्त डीजी कैलाश मकवाना के ट्रांसफर पर बेट...

[5000 rows x 1 columns]

In [ ]:
# stopWords = open("/content/drive/MyDrive/ML Assignment 2 DataSet/stop_words.txt", "r")
# stop = stopWords.read()
# stop = stop.split("\n")
# tweet =  tweets_cleaned.iloc[1]['Tweets']
# tweet = " ".join(tweet.split())
# #tweet = tweet.s.str.split()
# #tweet  = [word for word in tweet if word not in stop]
# tweet

In [ ]:
# query = 'What is hello'
# stopwords = ['what', 'who', 'is', 'a', 'at', 'is', 'he']
# querywords = query.split()

# resultwords  = [word for word in querywords if word.lower() not in stopwords]
# result = ' '.join(resultwords)

# print(result)

tweets_cleaned = tweets_df[['Tweets']].copy()
tweets_cleaned['Tweets'] = tweets_cleaned['Tweets'].str.lower()

stopWords = open("/content/drive/MyDrive/ML Assignment 2 DataSet/stop_words.txt", "r")
stop = stopWords.read()
stop = stop.split("\n")

# punctuated = str.maketrans('', '', string.punctuation)
# stripped = [w.translate(punctuated) for w in lowered_set[0]]
# print(stripped[:100])
#lowered_set[0]
#tweets_df['Tweets'] =tweets_df['Tweets'].str.replace('[{}]'.format(string.punctuation), '')
# tweets_cleaned =tweets_cleaned.str.replace(r'[^\w\s]+', '')
#.str.split()
clean_tweets = []
for tweet in tweets_cleaned['Tweets']:
    ##Here's where all the cleaning takes place


    #tweet = tweet.apply(lambda x: [item for item in x if item not in stop])
    #tweet = re.sub("@[A-Za-z0-9]+","",tweet) #Remove @ sign

    tweet = re.sub("@[A-Za-z0-9_]+","", tweet)  #remove mentions
    tweet = re.sub("#[A-Za-z0-9_]+","", tweet)  #remove hashtags

    tweet = re.sub(r"(?:\@|http?\://|https?\://|www)\S+", "", tweet) #Remove http links
    tweet = re.sub("[^a-z0-9]"," ", tweet)
    tweet = " ".join(tweet.split())
    #tweet = tweet.split()
    #tweet  = [word for word in tweet if word not in stop]
    #tweet = ''.join(c for c in tweet if c not in emoji.UNICODE_EMOJI) #Remove Emojis
    #tweet = tweet.replace("#", "").replace("_", " ") #Remove hashtag sign but keep the text
    clean_tweets.append(tweet)

tweets_cleaned['Tweets'] = clean_tweets
tweets_cleaned['Tweets'] =tweets_cleaned['Tweets'].str.replace(r'[^\w\s]+', '') #r  emove anything other than alpha numerics

tweets_cleaned['Tweets'].replace('', np.nan, inplace=True)
tweets_cleaned.dropna(subset=['Tweets'], inplace=True)
tweets_cleaned

<ipython-input-139-edd28a5c2ba1>:45: FutureWarning: The default value of regex will change from True to False in a future version.
  tweets_cleaned['Tweets'] =tweets_cleaned['Tweets'].str.replace(r'[^\w\s]+', '') #remove anything other than alpha numerics


Tweets
0     taylors bring in the new year with me i m perf...
1                                 they day party set up
2                                        me in the club
3     being able to speak well has gotten me very fa...
4        pull out the weed and everyone becomes friends
...                                                 ...
4993                                              watch
4996                                               live
4997                                       live pm modi
4998                                      7 30 4 30 abp
4999                                  proud of you papa

[4496 rows x 1 columns]

In [ ]:
stopWords = open("/content/drive/MyDrive/ML Assignment 2 DataSet/stop_words.txt", "r")
stop = stopWords.read()
stop = stop.split("\n")
#tweet =  tweets_cleaned.iloc[1]['Tweets']
#tweet = " ".join(tweet.split())
#tweet = tweet.s.str.split()
#tweet  = [word for word in tweet if word not in stop]
#tweet
tweets_cleaned['Tweet_without_stopwords'] = tweets_cleaned['Tweets'].apply(lambda x: ' '.join([word for word in x.split() if word not in stop]))

In [ ]:
tweets_cleaned

Tweets  \
0     taylors bring in the new year with me i m perf...   
1                                 they day party set up   
2                                        me in the club   
3     being able to speak well has gotten me very fa...   
4        pull out the weed and everyone becomes friends   
...                                                 ...   
4993                                              watch   
4996                                               live   
4997                                       live pm modi   
4998                                      7 30 4 30 abp   
4999                                  proud of you papa   

                                Tweet_without_stopwords  
0     taylors bring new year performing hosted tune ...  
1                                         day party set  
2                                                  club  
3                       able speak well gotten far life  
4                    pull weed everyone becomes friends  
...                                                 ...  
4993                                              watch  
4996                                               live  
4997                                       live pm modi  
4998                                      7 30 4 30 abp  
4999                                         proud papa  

[4496 rows x 2 columns]

In [ ]:
#saving task 2 file
tweets_cleaned['Tweet_without_stopwords'].to_csv('wizkhalifa_task2.csv',index=False) # relative position
path = '/content/drive/MyDrive/Project_Phase_1'
from google.colab import files
files.download("wizkhalifa_task2.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
#Task 3
# Splitting the Words
tweets_cleaned['Tweets_split'] = tweets_cleaned['Tweet_without_stopwords'].str.split()
tweets_cleaned

Tweets  \
0     taylors bring in the new year with me i m perf...   
1                                 they day party set up   
2                                        me in the club   
3     being able to speak well has gotten me very fa...   
4        pull out the weed and everyone becomes friends   
...                                                 ...   
4993                                              watch   
4996                                               live   
4997                                       live pm modi   
4998                                      7 30 4 30 abp   
4999                                  proud of you papa   

                                Tweet_without_stopwords  \
0     taylors bring new year performing hosted tune ...   
1                                         day party set   
2                                                  club   
3                       able speak well gotten far life   
4                    pull weed everyone becomes friends   
...                                                 ...   
4993                                              watch   
4996                                               live   
4997                                       live pm modi   
4998                                      7 30 4 30 abp   
4999                                         proud papa   

                                           Tweets_split  
0     [taylors, bring, new, year, performing, hosted...  
1                                     [day, party, set]  
2                                                [club]  
3                [able, speak, well, gotten, far, life]  
4              [pull, weed, everyone, becomes, friends]  
...                                                 ...  
4993                                            [watch]  
4996                                             [live]  
4997                                   [live, pm, modi]  
4998                                [7, 30, 4, 30, abp]  
4999                                      [proud, papa]  

[4496 rows x 3 columns]

In [ ]:
from sklearn.model_selection import train_test_split

train, test = train_test_split(tweets_cleaned, test_size=0.2,random_state=42 )

In [ ]:
x = train.iloc[1]['Tweets_split']

final_list = set()

final_list.update(x)
print(final_list)

{'shameful', 'service', 'terrible', 'customer'}


In [ ]:
test

Tweets  \
167   if you eat some hot shit and your stomach gets...   
1824  bjp invokes 2002 for ahmedabad 2022 congress f...   
564                              every day is different   
1473  external affairs minister dr s jaishankar meet...   
3665  i m so proud to be the face of bvlgari x her h...   
...                                                 ...   
4395                                               live   
1594  turncoats and rebels slug it out in gujarat po...   
1961  in congress stronghold of bayad independent ca...   
635                          shoulda sold bathing suits   
2250  an incredibly bright flash that appeared in th...   

                                Tweet_without_stopwords  \
167   eat hot shit stomach gets fucked take oil oregano   
1824  bjp invokes 2002 ahmedabad 2022 congress faces...   
564                                 every day different   
1473  external affairs minister dr jaishankar meets ...   
3665  proud face bvlgari x highness sheikha fatima b...   
...                                                 ...   
4395                                               live   
1594       turncoats rebels slug gujarat polls phase ii   
1961  congress stronghold bayad independent candidat...   
635                          shoulda sold bathing suits   
2250  incredibly bright flash appeared night sky feb...   

                                           Tweets_split  
167   [eat, hot, shit, stomach, gets, fucked, take, ...  
1824  [bjp, invokes, 2002, ahmedabad, 2022, congress...  
564                             [every, day, different]  
1473  [external, affairs, minister, dr, jaishankar, ...  
3665  [proud, face, bvlgari, x, highness, sheikha, f...  
...                                                 ...  
4395                                             [live]  
1594  [turncoats, rebels, slug, gujarat, polls, phas...  
1961  [congress, stronghold, bayad, independent, can...  
635                     [shoulda, sold, bathing, suits]  
2250  [incredibly, bright, flash, appeared, night, s...  

[900 rows x 3 columns]

In [ ]:

vocabulary_list = set()

for line in train['Tweets_split']:

  vocabulary_list.update(line)
len_vector = len(vocabulary_list)
print(len(vocabulary_list))

9267


In [ ]:
#Index dictionary to assign an index to each word in vocabulary
from collections import defaultdict
index_word = {}
i = 0
for word in vocabulary_list:
    index_word[word] = i
    i += 1

print(index_word)

{'harmful': 0, 'muslim': 1, 'casting': 2, 'surface': 3, 'posco': 4, 'amosov': 5, 'tryna': 6, 'plan': 7, 'electronic': 8, 'turf': 9, 'study': 10, 'quirky': 11, 'pesticides': 12, 'passion': 13, 'dominique': 14, 'operating': 15, 'kurdish': 16, 'forget': 17, '80s': 18, 'wc': 19, 'acquitted': 20, 'superagers': 21, 'university': 22, 'penalty': 23, 'girls': 24, 'nick': 25, 'income': 26, 'yrs': 27, 'mix': 28, 'economy': 29, 'electoral': 30, 'nagpur': 31, 'know': 32, 'swiss': 33, 'minecraft': 34, 'paccs': 35, 'pastor': 36, 'neighbour': 37, 'fever': 38, 'encompasses': 39, 'advises': 40, 'lower': 41, 'fruit': 42, 'collective': 43, 'saxena': 44, 'allahabad': 45, 'missions': 46, 'ipad': 47, 'steaming': 48, 'songs': 49, 'osteopathic': 50, 'discoverla': 51, 'e': 52, 'hardly': 53, 'fair': 54, 'density': 55, '218': 56, 'aircraft': 57, 'demolition': 58, 'corleone': 59, 'unquestioned': 60, 'reluctantly': 61, 'muzaffarpur': 62, 'loyalties': 63, 'produced': 64, 'flooding': 65, 'age': 66, 'rolled': 67, 'ski

In [ ]:
train_bow = train['Tweet_without_stopwords'].head(10)

In [ ]:
def bag_of_words(sent):
    count_dict = defaultdict(int)
    vec = np.zeros(len_vector)
    #print(sent)
    for item in sent:
      if item in vocabulary_list:
       count_dict[item] += 1

      for key,item in count_dict.items():
          vec[index_word[key]] = item
    for i, num in enumerate(vec):
      vec[i] = num + 1
    return vec

In [ ]:
#print(count_dict.items())

In [ ]:
x=train['Tweet_without_stopwords'].head(2)
x

4674                                            watch mcd
3082    discussing kapoor sisters 11 years aisha santu...
Name: Tweet_without_stopwords, dtype: object

In [ ]:
train_array =train_bow.to_numpy()
print(train_array[0])
for item in train_array[0]:
  print(item)

['watch', 'mcd']
watch
mcd


In [ ]:
for t in train_array:
  print(t)

['watch', 'mcd']
['discussing', 'kapoor', 'sisters', '11', 'years', 'aisha', 'santu', 'misra', 'rhea', 'kapoor', 'dark', 'room', 'india', 'tomorrow', '6', 'aug', '10', '00', 'pm', 'gmt', '5', '30', 'join', 'us']
['got', 'time', 'argue', 'ima', 'u', 'right', 'fuck', 'outta', 'u']
['top', 'european', 'union', 'official', 'warned', 'twitter', 'owner', 'elon', 'musk', 'social', 'media', 'platform', 'must', 'take', 'significant', 'steps', 'comply', 'eu', 'content', 'moderation', 'laws', 'european', 'officials', 'monitoring', 'closely', 'compliance']
['illicit', 'booze', 'factories', 'big', 'trouble', 'state', 'punjab', 'admits', 'sc']
['piece', 'favorite', 'collection']
['5', '30']
['batman', 'superman', 'son', 'heung', 'min', 'flying', 'wing', 'south', 'korea']
['lapid', 'fellow', 'foreign', 'jurors', 'back', 'kashmir', 'files', 'remark']
['curation', 'could', 'better', 'books', 'mentioned', 'mediocre', 'best']


In [ ]:
train_array

array([list(['watch', 'mcd']),
       list(['discussing', 'kapoor', 'sisters', '11', 'years', 'aisha', 'santu', 'misra', 'rhea', 'kapoor', 'dark', 'room', 'india', 'tomorrow', '6', 'aug', '10', '00', 'pm', 'gmt', '5', '30', 'join', 'us']),
       list(['got', 'time', 'argue', 'ima', 'u', 'right', 'fuck', 'outta', 'u']),
       list(['top', 'european', 'union', 'official', 'warned', 'twitter', 'owner', 'elon', 'musk', 'social', 'media', 'platform', 'must', 'take', 'significant', 'steps', 'comply', 'eu', 'content', 'moderation', 'laws', 'european', 'officials', 'monitoring', 'closely', 'compliance']),
       list(['illicit', 'booze', 'factories', 'big', 'trouble', 'state', 'punjab', 'admits', 'sc']),
       list(['piece', 'favorite', 'collection']), list(['5', '30']),
       list(['batman', 'superman', 'son', 'heung', 'min', 'flying', 'wing', 'south', 'korea']),
       list(['lapid', 'fellow', 'foreign', 'jurors', 'back', 'kashmir', 'files', 'remark']),
       list(['curation', 'could', 

In [ ]:
import sys

In [ ]:
print(train_array[0])

['watch', 'mcd']


In [ ]:
#print 10 features for the train set
# print(len(np_array))
# train_set = np.empty()

train_set = bag_of_words(train_array[0])
# train_set = np.vstack((train_set, bag_of_words(train_array[1])))
# train_set = np.vstack((train_set, bag_of_words(train_array[2])))
# train_set = np.vstack((train_set, bag_of_words(train_array[3])))
# train_set = np.vstack((train_set, bag_of_words(train_array[4])))
# train_set = np.vstack((train_set, bag_of_words(train_array[5])))
# train_set = np.vstack((train_set, bag_of_words(train_array[6])))
# train_set = np.vstack((train_set, bag_of_words(train_array[7])))
# train_set = np.vstack((train_set, bag_of_words(train_array[8])))
# train_set = np.vstack((train_set, bag_of_words(train_array[9])))

for tweet in train_array:
  print(tweet)
  train_set = np.vstack((train_set, bag_of_words(tweet)))


# with np.printoptions(threshold=sys.maxsize):
train_set = train_set[1:,:]
print(train_set)
print(np.sum(train_set))

['watch', 'mcd']
['discussing', 'kapoor', 'sisters', '11', 'years', 'aisha', 'santu', 'misra', 'rhea', 'kapoor', 'dark', 'room', 'india', 'tomorrow', '6', 'aug', '10', '00', 'pm', 'gmt', '5', '30', 'join', 'us']
['got', 'time', 'argue', 'ima', 'u', 'right', 'fuck', 'outta', 'u']
['top', 'european', 'union', 'official', 'warned', 'twitter', 'owner', 'elon', 'musk', 'social', 'media', 'platform', 'must', 'take', 'significant', 'steps', 'comply', 'eu', 'content', 'moderation', 'laws', 'european', 'officials', 'monitoring', 'closely', 'compliance']
['illicit', 'booze', 'factories', 'big', 'trouble', 'state', 'punjab', 'admits', 'sc']
['piece', 'favorite', 'collection']
['5', '30']
['batman', 'superman', 'son', 'heung', 'min', 'flying', 'wing', 'south', 'korea']
['lapid', 'fellow', 'foreign', 'jurors', 'back', 'kashmir', 'files', 'remark']
['curation', 'could', 'better', 'books', 'mentioned', 'mediocre', 'best']
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...

In [ ]:
for x in train_set[1]:
  if x>1:
    print(x)

2.0
2.0
2.0
3.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0
2.0


In [ ]:
  test_bow = test['Tweet_without_stopwords'].head(10)
  test_bow

1671    [around, 30, voters, turnout, recorded, till, ...
3783                                              [quick]
4615             [ideas, india, edition, 2, coming, soon]
4196                                              [first]
498          [roll, read, always, easy, mean, stop, doin]
3085             [posted, photo, london, united, kingdom]
1947    [politics, individuals, bjp, makes, 1, person,...
161           [crazy, even, tell, one, weed, trash, days]
4006                                              [watch]
2787    [past, year, giant, clock, doha, counting, ope...
Name: Tweet_without_stopwords, dtype: object

In [ ]:
 #10 features for the test set
test_bow = test['Tweet_without_stopwords'].head(10)
test_array =test_bow.to_numpy()

test_set = bag_of_words(test_array[0])
test_set = np.vstack((test_set, bag_of_words(test_array[1])))
test_set = np.vstack((test_set, bag_of_words(test_array[2])))
test_set = np.vstack((test_set, bag_of_words(test_array[3])))
test_set = np.vstack((test_set, bag_of_words(test_array[4])))
test_set = np.vstack((test_set, bag_of_words(test_array[5])))
test_set = np.vstack((test_set, bag_of_words(test_array[6])))
test_set = np.vstack((test_set, bag_of_words(test_array[7])))
test_set = np.vstack((test_set, bag_of_words(test_array[8])))
test_set = np.vstack((test_set, bag_of_words(test_array[9])))

print(test_set)
print(np.sum(test_set))

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
92421.0


In [ ]:
for x in test_set[2]:
  if x>1:
    print(x)


2.0
2.0
2.0
2.0
2.0
2.0


In [ ]:
pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 85 kB 2.4 MB/s 
     |████████████████████████████████| 5.8 MB 51.2 MB/s 
     |████████████████████████████████| 1.3 MB 46.6 MB/s 
     |████████████████████████████████| 182 kB 57.8 MB/s 
     |████████████████████████████████| 7.6 MB 49.4 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=dcdc75f982c89574b1a448889423bf7441ef8f760b5e4be4ee177d3d6ef72ab2
  Stored in directory: /root/.cache/pip/wheels/5e/6f/8c/d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
Successfully built sentence-transformers


In [ ]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('all-MiniLM-L6-v2')

tweets = tweets_cleaned['Tweet_without_stopwords'].tolist()

#Our sentences we like to encode
sentences = tweets
#Sentences are encoded by calling model.encode()
embeddings = model.encode(sentences)

#Print the embeddings
for sentence, embedding in zip(sentences, embeddings):
  print("Sentence:", sentence)
  print("Embedding:", embedding)
  print("")

In [ ]:

from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn.impute import SimpleImputer

In [ ]:
# Create features and target

# Create training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.3, random_state=4)

# Initialize a model with 5 neighbors
knn = KNeighborsClassifier(n_neighbors=3)

# Fit and predict
knn.fit(X_train, y_train)

predictions = knn.predict(X_test)